#!/usr/bin/env node
// Builds src/engine/suppliers.js: for the GoBricks (GDS) compatible-brick line, the GDS number of each
// part the engine uses and the colors GoBricks makes, from the public-domain (CC0) conversion table at
// github.com/mnemocron/GoBricksPart-API. The engine uses it for designs with "supplier": "gobricks";
// the viewer shows GDS numbers. GoBricks' own upload tool (webrick.com) has the final word on stock.
//   node scripts/gobricks.js           (downloads to .gobricks-cache/ on first run)
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const CACHE = path.join(ROOT, '.gobricks-cache');
const OUT = path.join(ROOT, 'src/engine/suppliers.js');
const RAW = 'https://raw.githubusercontent.com/mnemocron/GoBricksPart-API/main/';
// BrickLink numbers the table lists under an older or newer mold number
const ALIAS = { '3070b': ['3070'], '3069b': ['3069'], '3068b': ['3068'], '3062b': ['3062'], 4073: ['6141'], 4032: ['4032a', '4032b'] };

async function get(name) {
  const file = path.join(CACHE, name);
  if (!fs.existsSync(file)) {
    const res = await fetch(RAW + name);
    if (!res.ok) throw new Error(`Download failed: ${name} (${res.status})`);
    fs.mkdirSync(CACHE, { recursive: true }); fs.writeFileSync(file, await res.text());
  }
  return fs.readFileSync(file, 'utf8').replace(/^﻿/, '').trim().split(/\r?\n/).map((l) => l.split(','));
}

(async () => {
  const { SIZE_PARTS, SPECIAL, COLORS } = require('../src/engine/engine.js');
  const gds = new Map((await get('gobrick_conversion_table.csv')).map(([lego, g]) => [lego, g]));
  const colorRows = (await get('color_table.csv')).slice(1); // LEGO, BrickLink, Gobricks, LDD name, name
  const ours = new Set();
  for (const kind of Object.values(SIZE_PARTS)) for (const no of Object.values(kind)) ours.add(no);
  for (const s of Object.values(SPECIAL)) { ours.add(s.no); if (s.glass) ours.add(s.glass); }
  for (const b of ['3811', '4186']) ours.add(b); // baseplates
  const parts = {};
  for (const no of ours) { const g = gds.get(no) || (ALIAS[no] || []).map((a) => gds.get(a)).find(Boolean); if (g) parts[no] = g; }
  const blColors = new Set(colorRows.map((r) => r[1]));
  const colors = Object.keys(COLORS).filter((c) => blColors.has(String(COLORS[c].bl)));
  const missing = [...ours].filter((no) => !parts[no]);
  fs.writeFileSync(OUT, `// Compatible-brick suppliers the engine can hold a design to ("supplier" on the design). GoBricks (GDS):
// the GDS number of each part the engine uses that GoBricks makes, and the palette colors it makes,
// from the CC0 table at github.com/mnemocron/GoBricksPart-API. Generated by scripts/gobricks.js.
const SUPPLIERS = ${JSON.stringify({ gobricks: { name: 'GoBricks', order: 'https://www.webrick.com/part-list-upload-tool', parts, colors } })};
if (typeof module !== 'undefined') module.exports = { SUPPLIERS };
`);
  console.log(`Wrote ${path.relative(ROOT, OUT)}: ${Object.keys(parts).length} of ${ours.size} parts, ${colors.length} of ${Object.keys(COLORS).length} colors. Not at GoBricks: ${missing.join(', ') || 'none'}; colors: ${Object.keys(COLORS).filter((c) => !colors.includes(c)).join(', ')}`);
})().catch((e) => { console.error(e.message); process.exit(1); });
